---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: of_PR
  image: plugins/gcr
  settings:
    dry_run: true
    registry: docker.io
    repo: ciscocx/of
  when:
    event:
    - pull_request
    ref:
    - refs/heads/master
    - refs/tags/*

- name: of
  image: plugins/gcr
  settings:
    auto_tag: true
    json_key:
      from_secret: gcr_credentials
    registry: docker.io
    repo: ciscocx/of
  when:
    event:
    - tag
    - push
    ref:
    - refs/heads/master
    - refs/tags/*

- name: send_notification
  image: plugins/slack
  settings:
    channel: drone-ci
    icon_url: https://raw.githubusercontent.com/drone/brand/master/logos/png/dark/drone-logo-png-dark-64.png
    username: Drone CI
    webhook:
      from_secret: slack_webhook
  when:
    status:
    - failure

...
