---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: run_unittests
  image: golang:1.13.1-stretch
  when:
    event:
      - pull_request
      - push
  commands:
    - make test
  depends_on: [clone]

- name: build_docker_image_PR
  image: plugins/docker
  settings:
    dry_run: true
    registry: docker.io
    repo: ciscocx/of
  when:
    event:
    - pull_request
    - push
  branches:
    exclude: master
  depends_on: [clone]

- name: of
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: docker.io
    repo: ciscocx/of
  when:
    event:
    - tag
    - push
    ref:
    - refs/heads/master
    - refs/tags/*

- name: send_notification
  image: plugins/slack
  settings:
    channel: drone-ci
    icon_url: https://raw.githubusercontent.com/drone/brand/master/logos/png/dark/drone-logo-png-dark-64.png
    username: Drone CI
    webhook:
      from_secret: slack_webhook
  when:
    status:
    - failure
    ref:
    - refs/heads/master
    - refs/tags/*


---
kind: signature
hmac: 64e0f6604f25b201ad4e912d591566b703891a816c4089a90266730618000d55

...
