"global":
  "resolve_timeout": "5m"
"receivers":
- "name": "default-receiver"
  "webhook_configs":
  - "url": "http://[::1]:9097/webhook"
"route":
  "group_by":
  - "alert_fingerprint"
  - "alertname"
  - "source_hostname"
  "group_interval": "1s"
  "group_wait": "0s"
  "receiver": "default-receiver"
  "repeat_interval": "8736h"
  "routes":
  - "continue": true
    "receiver": "default-receiver"
